language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install coveralls
  - pip install pytest pytest-cov
  - pip install --only-binary=numpy numpy
  - pip install --only-binary=scipy scipy
  - pip install --only-binary=netcdf4 netcdf4
  - pip install affine
install:
  - python setup.py install
script:
  - pytest --cov --cov-report=xml:$(pwd)/coverage.xml
after_success:
  - coveralls
